# Generated by Django 2.0.6 on 2018-07-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simhash_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permutation',
            name='bits_rotated',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='permutation',
            name='hash',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='simhash',
            name='hash',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='simhash',
            name='method',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='simhash',
            name='source',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
